BACKUP_MAGIC = b"CONF"
BACKUP_FORMAT_VERSION = 1

HEADER_LENGTH_BYTES = 4
GCM_NONCE_BYTES = 12
GCM_TAG_BYTES = 16
MAX_HEADER_BYTES = 64 * 1024

HUMAN_KEY_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"
HUMAN_KEY_DATA_LENGTH = 52
HUMAN_KEY_GROUP_SIZE = 4
HUMAN_KEY_MAX_VALUE = 1 << 256
HUMAN_KEY_SEPARATOR = "-"
