"""normalize empty compiled access rule sets

Revision ID: 0b73fbf3e15a
Revises: 9ea550607d48
Create Date: 2026-07-08 19:14:14.467650

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0b73fbf3e15a"
down_revision: Union[str, Sequence[str], None] = "9ea550607d48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_nodes_access_rule_set_id"),
            ["access_rule_set_id"],
            unique=False,
        )

    # ### end Alembic commands ###
    _normalize_compiled_access_rule_sets()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nodes_access_rule_set_id"))

    # ### end Alembic commands ###


def _normalize_compiled_access_rule_sets() -> None:
    op.execute(
        sa.text(
            """
            UPDATE nodes
            SET access_rule_set_id = NULL
            WHERE access_rule_set_id IS NOT NULL
              AND NOT EXISTS (
                  SELECT 1
                  FROM compiled_access_rule_sets
                  WHERE compiled_access_rule_sets.id = nodes.access_rule_set_id
                    AND compiled_access_rule_sets.node_id = nodes.id
              )
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE nodes
            SET access_rule_set_id = NULL
            WHERE access_rule_set_id IN (
                SELECT compiled_access_rule_sets.id
                FROM compiled_access_rule_sets
                LEFT JOIN compiled_access_rules
                  ON compiled_access_rules.rule_set_id = compiled_access_rule_sets.id
                GROUP BY compiled_access_rule_sets.id
                HAVING COUNT(compiled_access_rules.id) = 0
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            DELETE FROM compiled_access_rule_sets
            WHERE id NOT IN (
                SELECT access_rule_set_id
                FROM nodes
                WHERE access_rule_set_id IS NOT NULL
            )
            """
        )
    )
