"""limit pending document reservations

Revision ID: 0c1a13dc091a
Revises: 99143e9cb883
Create Date: 2026-07-27 22:00:05.977315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1a13dc091a'
down_revision: Union[str, Sequence[str], None] = '99143e9cb883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_creation_throttles',
    sa.Column('scope', sa.VARCHAR(length=16), nullable=False),
    sa.Column('identity', sa.VARCHAR(length=256), nullable=False),
    sa.Column('window_started_at', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'identity', name=op.f('pk_document_creation_throttles'))
    )
    with op.batch_alter_table('document_creation_throttles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_creation_throttles_last_attempt'), ['last_attempt'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_creation_throttles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_creation_throttles_last_attempt'))

    op.drop_table('document_creation_throttles')
    # ### end Alembic commands ###
