"""UserBlockEntry update

Revision ID: 148e5acbbe5c
Revises: e805605cbb30
Create Date: 2026-02-22 21:33:03.503801

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148e5acbbe5c'
down_revision: str | Sequence[str] | None = 'e805605cbb30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userblock_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('not_before', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('not_after', sa.Float(), nullable=False))
        batch_op.drop_column('expiry')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userblock_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry', sa.FLOAT(), nullable=False))
        batch_op.drop_column('not_after')
        batch_op.drop_column('not_before')

    # ### end Alembic commands ###
