"""store file size

Revision ID: 259175f08107
Revises: a50674184a2c
Create Date: 2026-06-17 13:06:26.982760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from include.config.settings import global_config
from include.providers.base import StorageProvider
from include.providers.storage import LocalStorageProvider


# revision identifiers, used by Alembic.
revision: str = '259175f08107'
down_revision: Union[str, Sequence[str], None] = 'a50674184a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_storage_provider() -> StorageProvider:
    match global_config["provider"]["storage"]:
        case "local":
            return LocalStorageProvider()
        case "s3":
            from include.providers.storage.s3 import S3StorageProvider

            s3_cfg = global_config["s3"]
            return S3StorageProvider(
                bucket_name=s3_cfg["bucket"],
                endpoint_url=s3_cfg["endpoint_url"],
                aws_access_key_id=s3_cfg["access_key_id"],
                aws_secret_access_key=s3_cfg["secret_access_key"],
                region_name=s3_cfg["region_name"],
            )
        case storage_type:
            raise ValueError(f"Unsupported storage provider type: {storage_type}")


def _fill_file_sizes() -> None:
    connection = op.get_bind()
    storage = _get_storage_provider()
    files = connection.execute(sa.text("SELECT id, path FROM files")).mappings()

    for file_record in files:
        try:
            size = storage.getsize(file_record["path"])
        except FileNotFoundError:
            continue

        connection.execute(
            sa.text("UPDATE files SET size = :size WHERE id = :id"),
            {"id": file_record["id"], "size": size},
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.BigInteger(), nullable=True))

    _fill_file_sizes()

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
