"""durable file deduplication queue

Revision ID: 31ab3daf4d6f
Revises: 697123ea4145
Create Date: 2026-07-28 11:54:45.761858

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31ab3daf4d6f"
down_revision: str | Sequence[str] | None = "697123ea4145"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_deduplication_tasks",
        sa.Column("file_id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.Float(), nullable=False),
        sa.Column("lease_owner", sa.VARCHAR(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.Float(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_time", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "phase IN (0, 1)",
            name="ck_file_deduplication_tasks_phase_value",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_file_deduplication_tasks_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "file_id", name=op.f("pk_file_deduplication_tasks")
        ),
    )
    with op.batch_alter_table("file_deduplication_tasks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_file_deduplication_tasks_available_lease",
            ["available_at", "lease_expires_at"],
            unique=False,
        )

    with op.batch_alter_table("document_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_revisions_file_id"),
            ["file_id"],
            unique=False,
        )

    with op.batch_alter_table("file_tasks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_file_tasks_file_id_mode_status",
            ["file_id", "mode", "status"],
            unique=False,
        )

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.create_index(
            "ix_files_sha256_active_created_time_id",
            ["sha256", "active", "created_time", "id"],
            unique=False,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_avatar_id"), ["avatar_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_avatar_id"))

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index("ix_files_sha256_active_created_time_id")

    with op.batch_alter_table("file_tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_file_tasks_file_id_mode_status")

    with op.batch_alter_table("document_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_revisions_file_id"))

    with op.batch_alter_table("file_deduplication_tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_file_deduplication_tasks_available_lease")

    op.drop_table("file_deduplication_tasks")
    # ### end Alembic commands ###
