"""string compiled access rule group ids

Revision ID: 3c105b0f959d
Revises: e37338db17cc
Create Date: 2026-07-07 20:10:24.861700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c105b0f959d"
down_revision: Union[str, Sequence[str], None] = "e37338db17cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    referential_integrity_state = _disable_referential_integrity(conn)
    try:
        with op.batch_alter_table(
            "compiled_access_rule_groups", schema=None
        ) as batch_op:
            batch_op.alter_column(
                "id",
                existing_type=sa.INTEGER(),
                type_=sa.VARCHAR(length=32),
                existing_nullable=False,
            )

        with op.batch_alter_table(
            "compiled_access_rule_memberships", schema=None
        ) as batch_op:
            batch_op.alter_column(
                "group_id",
                existing_type=sa.INTEGER(),
                type_=sa.VARCHAR(length=32),
                existing_nullable=False,
            )

        with op.batch_alter_table(
            "compiled_access_rule_rights", schema=None
        ) as batch_op:
            batch_op.alter_column(
                "group_id",
                existing_type=sa.INTEGER(),
                type_=sa.VARCHAR(length=32),
                existing_nullable=False,
            )
    finally:
        _restore_referential_integrity(conn, referential_integrity_state)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    referential_integrity_state = _disable_referential_integrity(conn)
    try:
        _rewrite_group_ids_as_numeric_strings(conn)

        with op.batch_alter_table(
            "compiled_access_rule_rights", schema=None
        ) as batch_op:
            batch_op.alter_column(
                "group_id",
                existing_type=sa.VARCHAR(length=32),
                type_=sa.INTEGER(),
                existing_nullable=False,
            )

        with op.batch_alter_table(
            "compiled_access_rule_memberships", schema=None
        ) as batch_op:
            batch_op.alter_column(
                "group_id",
                existing_type=sa.VARCHAR(length=32),
                type_=sa.INTEGER(),
                existing_nullable=False,
            )

        with op.batch_alter_table(
            "compiled_access_rule_groups", schema=None
        ) as batch_op:
            batch_op.alter_column(
                "id",
                existing_type=sa.VARCHAR(length=32),
                type_=sa.INTEGER(),
                existing_nullable=False,
            )
    finally:
        _restore_referential_integrity(conn, referential_integrity_state)

    # ### end Alembic commands ###


def _disable_referential_integrity(conn) -> bool | None:
    if conn.dialect.name == "sqlite":
        enabled = bool(conn.exec_driver_sql("PRAGMA foreign_keys").scalar())
        conn.exec_driver_sql("PRAGMA foreign_keys=OFF")
        return enabled
    if conn.dialect.name == "mysql":
        enabled = bool(conn.exec_driver_sql("SELECT @@FOREIGN_KEY_CHECKS").scalar())
        conn.exec_driver_sql("SET FOREIGN_KEY_CHECKS=0")
        return enabled
    return None


def _restore_referential_integrity(conn, enabled: bool | None) -> None:
    if enabled is None:
        return
    if conn.dialect.name == "sqlite":
        conn.exec_driver_sql(f"PRAGMA foreign_keys={'ON' if enabled else 'OFF'}")
    elif conn.dialect.name == "mysql":
        conn.exec_driver_sql(f"SET FOREIGN_KEY_CHECKS={1 if enabled else 0}")


def _rewrite_group_ids_as_numeric_strings(conn) -> None:
    groups = sa.table(
        "compiled_access_rule_groups",
        sa.column("id", sa.String),
        sa.column("rule_id", sa.Integer),
        sa.column("group_index", sa.Integer),
    )
    rights = sa.table(
        "compiled_access_rule_rights",
        sa.column("group_id", sa.String),
    )
    memberships = sa.table(
        "compiled_access_rule_memberships",
        sa.column("group_id", sa.String),
    )

    ordered_ids = [
        row[0]
        for row in conn.execute(
            sa.select(groups.c.id).order_by(groups.c.rule_id, groups.c.group_index)
        )
    ]
    mappings = [(old_id, str(index)) for index, old_id in enumerate(ordered_ids, 1)]

    temp_mappings = [
        (old_id, f"tmp_downgrade_{index}")
        for index, (old_id, _new_id) in enumerate(mappings, 1)
    ]
    for old_id, temp_id in temp_mappings:
        conn.execute(
            rights.update()
            .where(rights.c.group_id == old_id)
            .values(group_id=temp_id)
        )
        conn.execute(
            memberships.update()
            .where(memberships.c.group_id == old_id)
            .values(group_id=temp_id)
        )
        conn.execute(groups.update().where(groups.c.id == old_id).values(id=temp_id))

    for (_old_id, new_id), (_temp_old_id, temp_id) in zip(
        mappings, temp_mappings, strict=True
    ):
        conn.execute(
            rights.update()
            .where(rights.c.group_id == temp_id)
            .values(group_id=new_id)
        )
        conn.execute(
            memberships.update()
            .where(memberships.c.group_id == temp_id)
            .values(group_id=new_id)
        )
        conn.execute(groups.update().where(groups.c.id == temp_id).values(id=new_id))
