"""feature keyrings

Revision ID: 436b0d3452b6
Revises: 9c6ab2902b6e
Create Date: 2026-02-20 20:51:04.098178

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436b0d3452b6'
down_revision: str | Sequence[str] | None = '9c6ab2902b6e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyrings',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name=op.f('fk_keyrings_username_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyrings'))
    )
    with op.batch_alter_table('keyrings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyrings_username'), ['username'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preference_dek_id', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_preference_dek_id'), ['preference_dek_id'])
        batch_op.create_foreign_key(
            batch_op.f('fk_users_preference_dek_id_keyrings'),
            'keyrings',
            ['preference_dek_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_preference_dek_id_keyrings'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_users_preference_dek_id'), type_='unique')
        batch_op.drop_column('preference_dek_id')

    with op.batch_alter_table('keyrings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyrings_username'))

    op.drop_table('keyrings')
    # ### end Alembic commands ###
