"""rename traffic throttle tables

Revision ID: 5b4437a79292
Revises: c14bc87dd3f9
Create Date: 2026-04-29 16:59:28.663899

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4437a79292'
down_revision: str | Sequence[str] | None = 'c14bc87dd3f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_throttles',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username', 'ip_address', name=op.f('pk_login_throttles'))
    )
    with op.batch_alter_table('login_throttles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_throttles_ip_address'), ['ip_address'], unique=False)

    op.create_table('traffic_throttles',
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip_address', name=op.f('pk_traffic_throttles'))
    )
    op.drop_table('ip_login_security')
    with op.batch_alter_table('login_security', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_security_ip_address'))

    op.drop_table('login_security')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_security',
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('failed_attempts', sa.INTEGER(), nullable=False),
    sa.Column('last_attempt', sa.DATETIME(), nullable=False),
    sa.Column('locked_until', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('username', 'ip_address', name=op.f('pk_login_security'))
    )
    with op.batch_alter_table('login_security', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_security_ip_address'), ['ip_address'], unique=False)

    op.create_table('ip_login_security',
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('failed_attempts', sa.INTEGER(), nullable=False),
    sa.Column('last_attempt', sa.DATETIME(), nullable=False),
    sa.Column('locked_until', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('ip_address', name=op.f('pk_ip_login_security'))
    )
    op.drop_table('traffic_throttles')
    with op.batch_alter_table('login_throttles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_throttles_ip_address'))

    op.drop_table('login_throttles')
    # ### end Alembic commands ###
