"""implement marked deletion

Revision ID: 5d459d56bf38
Revises: 4d21b1e591d3
Create Date: 2026-03-12 13:07:13.043343

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d459d56bf38'
down_revision: str | Sequence[str] | None = '4d21b1e591d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table('document_revisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('status_operation_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_status_operation_id'), ['status_operation_id'], unique=False)

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('status_operation_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_folders_status_operation_id'), ['status_operation_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folders_status_operation_id'))
        batch_op.drop_column('status_operation_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status_operation_id'))
        batch_op.drop_column('status_operation_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('document_revisions', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
