"""add user status comments

Revision ID: 6664804d2860
Revises: 9050feb4200e
Create Date: 2026-07-15 22:27:28.307678

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6664804d2860"
down_revision: str | Sequence[str] | None = "9050feb4200e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status_comment_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_users_status_comment_id_comments"),
            "comments",
            ["status_comment_id"],
            ["comment_id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_users_status_comment_id_comments"), type_="foreignkey"
        )
        batch_op.drop_column("status_comment_id")

    # ### end Alembic commands ###
