"""adaptive document creation risk control

Revision ID: 697123ea4145
Revises: 55c97f57db3a
Create Date: 2026-07-28 10:48:09.693577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697123ea4145'
down_revision: Union[str, Sequence[str], None] = '55c97f57db3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_creation_ip_accounts',
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('username', sa.VARCHAR(length=256), nullable=False),
    sa.Column('last_attempt', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ip_address', 'username', name=op.f('pk_document_creation_ip_accounts'))
    )
    with op.batch_alter_table('document_creation_ip_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_creation_ip_accounts_last_attempt'), ['last_attempt'], unique=False)

    op.create_table('document_creation_rate_buckets',
    sa.Column('scope', sa.VARCHAR(length=16), nullable=False),
    sa.Column('identity', sa.VARCHAR(length=256), nullable=False),
    sa.Column('tokens', sa.Float(), nullable=False),
    sa.Column('last_refill_at', sa.Float(), nullable=False),
    sa.Column('denial_count', sa.Integer(), nullable=False),
    sa.Column('last_denied_at', sa.Float(), nullable=True),
    sa.Column('last_attempt', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'identity', name=op.f('pk_document_creation_rate_buckets'))
    )
    with op.batch_alter_table('document_creation_rate_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_creation_rate_buckets_last_attempt'), ['last_attempt'], unique=False)

    with op.batch_alter_table('document_creation_throttles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_creation_throttles_last_attempt'))

    op.drop_table('document_creation_throttles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_creation_throttles',
    sa.Column('scope', sa.VARCHAR(length=16), nullable=False),
    sa.Column('identity', sa.VARCHAR(length=256), nullable=False),
    sa.Column('window_started_at', sa.FLOAT(), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.Column('last_attempt', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'identity', name=op.f('pk_document_creation_throttles'))
    )
    with op.batch_alter_table('document_creation_throttles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_creation_throttles_last_attempt'), ['last_attempt'], unique=False)

    with op.batch_alter_table('document_creation_rate_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_creation_rate_buckets_last_attempt'))

    op.drop_table('document_creation_rate_buckets')
    with op.batch_alter_table('document_creation_ip_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_creation_ip_accounts_last_attempt'))

    op.drop_table('document_creation_ip_accounts')
    # ### end Alembic commands ###
