"""limit username length

Revision ID: 793312107aa5
Revises: 5d459d56bf38
Create Date: 2026-03-13 23:00:27.465446

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793312107aa5'
down_revision: str | Sequence[str] | None = '5d459d56bf38'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('keyrings', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('user_memberships', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('userblock_entries', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('userblock_entries', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('user_memberships', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('keyrings', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
