"""persist resumable upload checkpoint data

Revision ID: 7e576d23d5f9
Revises: 3c0666dd9068
Create Date: 2026-07-31 11:15:45.536969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e576d23d5f9'
down_revision: Union[str, Sequence[str], None] = '3c0666dd9068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_checkpoint_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_tasks', schema=None) as batch_op:
        batch_op.drop_column('upload_checkpoint_data')

    # ### end Alembic commands ###
