"""persist download chunk size

Revision ID: 8be3cdd47846
Revises: c93cef4aa664
Create Date: 2026-07-31 00:31:26.506733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be3cdd47846'
down_revision: Union[str, Sequence[str], None] = 'c93cef4aa664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_chunk_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_tasks', schema=None) as batch_op:
        batch_op.drop_column('download_chunk_size')

    # ### end Alembic commands ###
