"""add compiled access ruleset

Revision ID: 9ea550607d48
Revises: 96916de60390
Create Date: 2026-07-08 18:23:46.414585

"""
import secrets
import time
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea550607d48'
down_revision: Union[str, Sequence[str], None] = '96916de60390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compiled_access_rule_sets',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('node_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_compiled_access_rule_sets_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compiled_access_rule_sets'))
    )
    with op.batch_alter_table('compiled_access_rule_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compiled_access_rule_sets_node_id'), ['node_id'], unique=False)

    with op.batch_alter_table('compiled_access_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_set_id', sa.VARCHAR(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_compiled_access_rules_rule_set_id'), ['rule_set_id'], unique=False)

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_rule_set_id', sa.VARCHAR(length=32), nullable=True))

    _backfill_rule_sets()

    with op.batch_alter_table('compiled_access_rules', schema=None) as batch_op:
        batch_op.alter_column('rule_set_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_compiled_access_rules_node_id'))
        batch_op.drop_index('ix_compiled_access_rules_node_id_access')
        batch_op.drop_constraint(batch_op.f('fk_compiled_access_rules_node_id_nodes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_compiled_access_rules_rule_set_id_compiled_access_rule_sets'), 'compiled_access_rule_sets', ['rule_set_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('node_id')

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_nodes_access_rule_set_id_compiled_access_rule_sets', 'compiled_access_rule_sets', ['access_rule_set_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compiled_access_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_id', sa.VARCHAR(length=255), nullable=True))

    _restore_rule_node_ids()

    with op.batch_alter_table('compiled_access_rules', schema=None) as batch_op:
        batch_op.alter_column('node_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_compiled_access_rules_rule_set_id_compiled_access_rule_sets'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_compiled_access_rules_node_id_nodes'), 'nodes', ['node_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_compiled_access_rules_rule_set_id'))
        batch_op.create_index('ix_compiled_access_rules_node_id_access', ['node_id', 'access_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_compiled_access_rules_node_id'), ['node_id'], unique=False)
        batch_op.drop_column('rule_set_id')

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_nodes_access_rule_set_id_compiled_access_rule_sets', type_='foreignkey')
        batch_op.drop_column('access_rule_set_id')

    with op.batch_alter_table('compiled_access_rule_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compiled_access_rule_sets_node_id'))

    op.drop_table('compiled_access_rule_sets')
    # ### end Alembic commands ###


def _backfill_rule_sets() -> None:
    conn = op.get_bind()
    metadata = sa.MetaData()
    nodes = sa.Table(
        'nodes',
        metadata,
        sa.Column('id', sa.String()),
        sa.Column('access_rule_set_id', sa.String()),
    )
    rule_sets = sa.Table(
        'compiled_access_rule_sets',
        metadata,
        sa.Column('id', sa.String()),
        sa.Column('node_id', sa.String()),
        sa.Column('created_at', sa.Float()),
    )
    rules = sa.Table(
        'compiled_access_rules',
        metadata,
        sa.Column('id', sa.Integer()),
        sa.Column('node_id', sa.String()),
        sa.Column('rule_set_id', sa.String()),
    )

    node_ids = [
        row[0]
        for row in conn.execute(
            sa.select(rules.c.node_id)
            .select_from(rules.join(nodes, rules.c.node_id == nodes.c.id))
            .distinct()
            .order_by(rules.c.node_id)
        )
    ]
    for node_id in node_ids:
        rule_set_id = secrets.token_hex(16)
        conn.execute(
            rule_sets.insert().values(
                id=rule_set_id,
                node_id=node_id,
                created_at=time.time(),
            )
        )
        conn.execute(
            rules.update()
            .where(rules.c.node_id == node_id)
            .values(rule_set_id=rule_set_id)
        )
        conn.execute(
            nodes.update()
            .where(nodes.c.id == node_id)
            .values(access_rule_set_id=rule_set_id)
        )


def _restore_rule_node_ids() -> None:
    op.execute(
        """
        UPDATE compiled_access_rules
        SET node_id = (
            SELECT compiled_access_rule_sets.node_id
            FROM compiled_access_rule_sets
            WHERE compiled_access_rule_sets.id = compiled_access_rules.rule_set_id
        )
        """
    )
