"""optimize paginated document listing indexes

Revision ID: a5fa47f77246
Revises: 259175f08107
Create Date: 2026-07-01 13:39:40.963599

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5fa47f77246"
down_revision: str | Sequence[str] | None = "259175f08107"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_folders_parent_status_lower_name_id",
        "folders",
        ["parent_id", "status", sa.text("lower(name)"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_folders_status_lower_name_id",
        "folders",
        ["status", sa.text("lower(name)"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_folders_status_created_time_id",
        "folders",
        ["status", "created_time", "id"],
        unique=False,
    )
    op.create_index(
        "ix_documents_folder_status_lower_title_id",
        "documents",
        ["folder_id", "status", sa.text("lower(title)"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_documents_status_lower_title_id",
        "documents",
        ["status", sa.text("lower(title)"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_documents_status_created_time_id",
        "documents",
        ["status", "created_time", "id"],
        unique=False,
    )
    op.create_index(
        "ix_documents_current_revision_id",
        "documents",
        ["current_revision_id"],
        unique=False,
    )
    op.create_index(
        "ix_document_revisions_document_created_id",
        "document_revisions",
        ["document_id", "created_time", "id"],
        unique=False,
    )
    op.create_index(
        "ix_document_revisions_parent_revision_id",
        "document_revisions",
        ["parent_revision_id"],
        unique=False,
    )
    op.create_index(
        "ix_files_active_size_id",
        "files",
        ["active", "size", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_files_active_size_id", table_name="files")
    op.drop_index(
        "ix_document_revisions_parent_revision_id",
        table_name="document_revisions",
    )
    op.drop_index(
        "ix_document_revisions_document_created_id",
        table_name="document_revisions",
    )
    op.drop_index("ix_documents_current_revision_id", table_name="documents")
    op.drop_index("ix_documents_status_created_time_id", table_name="documents")
    op.drop_index("ix_documents_status_lower_title_id", table_name="documents")
    op.drop_index(
        "ix_documents_folder_status_lower_title_id",
        table_name="documents",
    )
    op.drop_index("ix_folders_status_created_time_id", table_name="folders")
    op.drop_index("ix_folders_status_lower_name_id", table_name="folders")
    op.drop_index("ix_folders_parent_status_lower_name_id", table_name="folders")
    # ### end Alembic commands ###
