"""indexing

Revision ID: a8eba9cf56e2
Revises: 9087c4861e3d
Create Date: 2026-04-05 11:30:00.146125

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8eba9cf56e2'
down_revision: str | Sequence[str] | None = '9087c4861e3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entries_logged_time'), ['logged_time'], unique=False)

    with op.batch_alter_table('object_access_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_access_entries_entity_identifier'), ['entity_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_access_entries_target_identifier'), ['target_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_access_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_access_entries_target_identifier'))
        batch_op.drop_index(batch_op.f('ix_object_access_entries_entity_identifier'))

    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_entries_logged_time'))

    # ### end Alembic commands ###
