"""add scheduling infrastructure

Revision ID: ab7efda19079
Revises: 7bddfba0d8aa
Create Date: 2026-09-02 19:31:10.164979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7efda19079'
down_revision: Union[str, Sequence[str], None] = '7bddfba0d8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduling_runtime_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), nullable=False),
    sa.Column('generation', sa.BigInteger(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Double(), nullable=False),
    sa.CheckConstraint("provider IN ('local', 'redis')", name='ck_scheduling_runtime_provider'),
    sa.CheckConstraint('generation > 0', name='ck_scheduling_generation_positive'),
    sa.CheckConstraint('id = 1', name='ck_scheduling_runtime_state_singleton'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduling_runtime_state'))
    )
    op.create_table('schedules',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('task_contract_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('trigger_data', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.Column('next_run_at', sa.Double(), nullable=True),
    sa.Column('active_execution_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('pending_scheduled_for', sa.Double(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', sa.Double(), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=256), nullable=False),
    sa.Column('updated_at', sa.Double(), nullable=False),
    sa.Column('deleted_at', sa.Double(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'completed', 'failed', 'deleted')", name='ck_schedules_status'),
    sa.CheckConstraint("trigger_type IN ('cron', 'date', 'interval')", name='ck_schedules_trigger_type'),
    sa.CheckConstraint('revision > 0', name='ck_schedules_revision_positive'),
    sa.CheckConstraint('task_contract_version > 0', name='ck_schedules_task_contract_version_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], name=op.f('fk_schedules_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], name=op.f('fk_schedules_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index('ix_schedules_due', ['enabled', 'status', 'next_run_at'], unique=False)

    op.create_table('schedule_executions',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('schedule_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('provider_generation', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_for', sa.Double(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=16), nullable=False),
    sa.Column('dispatch_state', sa.VARCHAR(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('retry_at', sa.Double(), nullable=True),
    sa.Column('lease_owner', sa.VARCHAR(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.Double(), nullable=True),
    sa.Column('started_at', sa.Double(), nullable=True),
    sa.Column('completed_at', sa.Double(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('created_at', sa.Double(), nullable=False),
    sa.CheckConstraint("dispatch_state IN ('pending', 'sent')", name='ck_schedule_executions_dispatch_state'),
    sa.CheckConstraint("state IN ('pending', 'running', 'retry_wait', 'succeeded', 'failed', 'cancelled')", name='ck_schedule_executions_state'),
    sa.CheckConstraint('attempt >= 0', name='ck_schedule_executions_attempt'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_schedule_executions_schedule_id_schedules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_executions')),
    sa.UniqueConstraint('schedule_id', 'scheduled_for', name='uq_schedule_executions_occurrence')
    )
    with op.batch_alter_table('schedule_executions', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_executions_claim', ['state', 'dispatch_state', 'retry_at', 'lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_executions_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_executions_schedule_id'))
        batch_op.drop_index('ix_schedule_executions_claim')

    op.drop_table('schedule_executions')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_schedules_due')

    op.drop_table('schedules')
    op.drop_table('scheduling_runtime_state')
    # ### end Alembic commands ###
