"""unify persistent rate limit state

Revision ID: af95e9bae5fc
Revises: 31ab3daf4d6f
Create Date: 2026-07-28 19:33:25.899823

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "af95e9bae5fc"
down_revision: str | Sequence[str] | None = "31ab3daf4d6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CREATION_NAMESPACE = "document_creation"
_BUCKET_COLUMNS = (
    ("scope", sa.String()),
    ("identity", sa.String()),
    ("tokens", sa.Float()),
    ("last_refill_at", sa.Float()),
    ("denial_count", sa.Integer()),
    ("last_denied_at", sa.Float()),
    ("last_attempt", sa.Float()),
)
_ACCOUNT_COLUMNS = (
    ("ip_address", sa.String()),
    ("username", sa.String()),
    ("last_attempt", sa.Float()),
)


def _tables():
    old_buckets = sa.table(
        "document_creation_rate_buckets",
        *(sa.column(name, type_) for name, type_ in _BUCKET_COLUMNS),
    )
    new_buckets = sa.table(
        "rate_limit_buckets",
        sa.column("namespace", sa.String()),
        *(sa.column(name, type_) for name, type_ in _BUCKET_COLUMNS),
    )
    old_accounts = sa.table(
        "document_creation_ip_accounts",
        *(sa.column(name, type_) for name, type_ in _ACCOUNT_COLUMNS),
    )
    new_accounts = sa.table(
        "risk_ip_accounts",
        sa.column("namespace", sa.String()),
        *(sa.column(name, type_) for name, type_ in _ACCOUNT_COLUMNS),
    )
    return old_buckets, new_buckets, old_accounts, new_accounts


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("rate_limit_buckets",
    sa.Column("namespace", sa.VARCHAR(length=64), nullable=False),
    sa.Column("scope", sa.VARCHAR(length=16), nullable=False),
    sa.Column("identity", sa.VARCHAR(length=256), nullable=False),
    sa.Column("tokens", sa.Float(), nullable=False),
    sa.Column("last_refill_at", sa.Float(), nullable=False),
    sa.Column("denial_count", sa.Integer(), nullable=False),
    sa.Column("last_denied_at", sa.Float(), nullable=True),
    sa.Column("last_attempt", sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint("namespace", "scope", "identity", name=op.f("pk_rate_limit_buckets"))
    )
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_buckets_last_attempt'), ['last_attempt'], unique=False)

    op.create_table("risk_ip_accounts",
    sa.Column('namespace', sa.VARCHAR(length=64), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('username', sa.VARCHAR(length=256), nullable=False),
    sa.Column('last_attempt', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('namespace', 'ip_address', 'username', name=op.f('pk_risk_ip_accounts'))
    )
    with op.batch_alter_table('risk_ip_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_ip_accounts_last_attempt'), ['last_attempt'], unique=False)

    old_buckets, new_buckets, old_accounts, new_accounts = _tables()
    connection = op.get_bind()
    connection.execute(
        new_buckets.insert().from_select(
            [column.name for column in new_buckets.c],
            sa.select(sa.literal(_CREATION_NAMESPACE), *old_buckets.c),
        )
    )
    connection.execute(
        new_accounts.insert().from_select(
            [column.name for column in new_accounts.c],
            sa.select(sa.literal(_CREATION_NAMESPACE), *old_accounts.c),
        )
    )

    with op.batch_alter_table('document_creation_ip_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_creation_ip_accounts_last_attempt'))

    op.drop_table('document_creation_ip_accounts')
    with op.batch_alter_table('document_creation_rate_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_creation_rate_buckets_last_attempt'))

    op.drop_table('document_creation_rate_buckets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_creation_rate_buckets',
    sa.Column('scope', sa.VARCHAR(length=16), nullable=False),
    sa.Column('identity', sa.VARCHAR(length=256), nullable=False),
    sa.Column('tokens', sa.FLOAT(), nullable=False),
    sa.Column('last_refill_at', sa.FLOAT(), nullable=False),
    sa.Column('denial_count', sa.INTEGER(), nullable=False),
    sa.Column('last_denied_at', sa.FLOAT(), nullable=True),
    sa.Column('last_attempt', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'identity', name=op.f('pk_document_creation_rate_buckets'))
    )
    with op.batch_alter_table('document_creation_rate_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_creation_rate_buckets_last_attempt'), ['last_attempt'], unique=False)

    op.create_table('document_creation_ip_accounts',
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('username', sa.VARCHAR(length=256), nullable=False),
    sa.Column('last_attempt', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('ip_address', 'username', name=op.f('pk_document_creation_ip_accounts'))
    )
    with op.batch_alter_table('document_creation_ip_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_creation_ip_accounts_last_attempt'), ['last_attempt'], unique=False)

    old_buckets, new_buckets, old_accounts, new_accounts = _tables()
    connection = op.get_bind()
    connection.execute(
        old_buckets.insert().from_select(
            [column.name for column in old_buckets.c],
            sa.select(*(new_buckets.c[name] for name, _type in _BUCKET_COLUMNS)).where(
                new_buckets.c.namespace == _CREATION_NAMESPACE
            ),
        )
    )
    connection.execute(
        old_accounts.insert().from_select(
            [column.name for column in old_accounts.c],
            sa.select(*(new_accounts.c[name] for name, _type in _ACCOUNT_COLUMNS)).where(
                new_accounts.c.namespace == _CREATION_NAMESPACE
            ),
        )
    )

    with op.batch_alter_table('risk_ip_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_ip_accounts_last_attempt'))

    op.drop_table('risk_ip_accounts')
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_buckets_last_attempt'))

    op.drop_table('rate_limit_buckets')
    # ### end Alembic commands ###
