"""compiled access rules

Revision ID: b8adfe3864ff
Revises: a5fa47f77246
Create Date: 2026-07-01 20:26:32.934194

"""
import json
from typing import Any, Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8adfe3864ff'
down_revision: Union[str, Sequence[str], None] = 'a5fa47f77246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compiled_access_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('target_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('source_rule_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('match_mode', sa.VARCHAR(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compiled_access_rules')),
    sa.UniqueConstraint('target_type', 'source_rule_id', name='uq_compiled_access_rules_target_source')
    )
    with op.batch_alter_table('compiled_access_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compiled_access_rules_access_type'), ['access_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_compiled_access_rules_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compiled_access_rules_target_type'), ['target_type'], unique=False)

    op.create_table('compiled_access_rule_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('group_index', sa.Integer(), nullable=False),
    sa.Column('match_mode', sa.VARCHAR(length=8), nullable=False),
    sa.Column('rights_match_mode', sa.VARCHAR(length=8), nullable=False),
    sa.Column('rights_empty', sa.Boolean(), nullable=False),
    sa.Column('groups_match_mode', sa.VARCHAR(length=8), nullable=False),
    sa.Column('groups_empty', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['compiled_access_rules.id'], name=op.f('fk_compiled_access_rule_groups_rule_id_compiled_access_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compiled_access_rule_groups'))
    )
    with op.batch_alter_table('compiled_access_rule_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compiled_access_rule_groups_rule_id'), ['rule_id'], unique=False)

    op.create_table('compiled_access_rule_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['compiled_access_rule_groups.id'], name=op.f('fk_compiled_access_rule_memberships_group_id_compiled_access_rule_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compiled_access_rule_memberships'))
    )
    with op.batch_alter_table('compiled_access_rule_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compiled_access_rule_memberships_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compiled_access_rule_memberships_group_name'), ['group_name'], unique=False)

    op.create_table('compiled_access_rule_rights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['compiled_access_rule_groups.id'], name=op.f('fk_compiled_access_rule_rights_group_id_compiled_access_rule_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compiled_access_rule_rights'))
    )
    with op.batch_alter_table('compiled_access_rule_rights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compiled_access_rule_rights_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compiled_access_rule_rights_permission'), ['permission'], unique=False)

    _backfill_compiled_access_rules()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compiled_access_rule_rights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compiled_access_rule_rights_permission'))
        batch_op.drop_index(batch_op.f('ix_compiled_access_rule_rights_group_id'))

    op.drop_table('compiled_access_rule_rights')
    with op.batch_alter_table('compiled_access_rule_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compiled_access_rule_memberships_group_name'))
        batch_op.drop_index(batch_op.f('ix_compiled_access_rule_memberships_group_id'))

    op.drop_table('compiled_access_rule_memberships')
    with op.batch_alter_table('compiled_access_rule_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compiled_access_rule_groups_rule_id'))

    op.drop_table('compiled_access_rule_groups')
    with op.batch_alter_table('compiled_access_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compiled_access_rules_target_type'))
        batch_op.drop_index(batch_op.f('ix_compiled_access_rules_target_id'))
        batch_op.drop_index(batch_op.f('ix_compiled_access_rules_access_type'))

    op.drop_table('compiled_access_rules')
    # ### end Alembic commands ###


def _as_match_mode(value: Any) -> str:
    return value if value in ("all", "any") else "all"


def _parse_rule_data(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        parsed = json.loads(value)
        return parsed if isinstance(parsed, dict) else {}
    return {}


def _required_items(group_data: dict[str, Any], key: str) -> list[str]:
    value = group_data.get(key, {})
    if not isinstance(value, dict):
        return []
    required = value.get("require", [])
    if not isinstance(required, list):
        return []
    return [str(item) for item in required]


def _backfill_one_rule(
    conn,
    *,
    rules_table,
    groups_table,
    rights_table,
    memberships_table,
    target_type: str,
    target_id: str,
    source_rule_id: int,
    access_type: str,
    rule_data: dict[str, Any],
) -> None:
    if not rule_data:
        return

    result = conn.execute(
        rules_table.insert().values(
            target_type=target_type,
            target_id=target_id,
            source_rule_id=source_rule_id,
            access_type=access_type,
            match_mode=_as_match_mode(rule_data.get("match", "all")),
        )
    )
    compiled_rule_id = result.inserted_primary_key[0]

    match_groups = rule_data.get("match_groups", [])
    if not isinstance(match_groups, list):
        return

    for index, group_data in enumerate(match_groups):
        if not isinstance(group_data, dict) or not group_data:
            continue

        rights_group = group_data.get("rights", {})
        if not isinstance(rights_group, dict):
            rights_group = {}
        groups_group = group_data.get("groups", {})
        if not isinstance(groups_group, dict):
            groups_group = {}

        required_rights = _required_items(group_data, "rights")
        required_groups = _required_items(group_data, "groups")
        rights_empty = not required_rights
        groups_empty = not required_groups
        match_mode = _as_match_mode(group_data.get("match", "all"))
        if rights_empty or groups_empty:
            match_mode = "all"

        result = conn.execute(
            groups_table.insert().values(
                rule_id=compiled_rule_id,
                group_index=index,
                match_mode=match_mode,
                rights_match_mode=_as_match_mode(rights_group.get("match", "all")),
                rights_empty=rights_empty,
                groups_match_mode=_as_match_mode(groups_group.get("match", "all")),
                groups_empty=groups_empty,
            )
        )
        compiled_group_id = result.inserted_primary_key[0]
        for permission in required_rights:
            conn.execute(
                rights_table.insert().values(
                    group_id=compiled_group_id,
                    permission=permission,
                )
            )
        for group_name in required_groups:
            conn.execute(
                memberships_table.insert().values(
                    group_id=compiled_group_id,
                    group_name=group_name,
                )
            )


def _backfill_compiled_access_rules() -> None:
    conn = op.get_bind()
    rules_table = sa.table(
        "compiled_access_rules",
        sa.column("id", sa.Integer),
        sa.column("target_type", sa.String),
        sa.column("target_id", sa.String),
        sa.column("source_rule_id", sa.Integer),
        sa.column("access_type", sa.String),
        sa.column("match_mode", sa.String),
    )
    groups_table = sa.table(
        "compiled_access_rule_groups",
        sa.column("id", sa.Integer),
        sa.column("rule_id", sa.Integer),
        sa.column("group_index", sa.Integer),
        sa.column("match_mode", sa.String),
        sa.column("rights_match_mode", sa.String),
        sa.column("rights_empty", sa.Boolean),
        sa.column("groups_match_mode", sa.String),
        sa.column("groups_empty", sa.Boolean),
    )
    rights_table = sa.table(
        "compiled_access_rule_rights",
        sa.column("group_id", sa.Integer),
        sa.column("permission", sa.String),
    )
    memberships_table = sa.table(
        "compiled_access_rule_memberships",
        sa.column("group_id", sa.Integer),
        sa.column("group_name", sa.String),
    )

    document_rules = sa.table(
        "document_access_rules",
        sa.column("id", sa.Integer),
        sa.column("document_id", sa.String),
        sa.column("access_type", sa.String),
        sa.column("rule_data", sa.JSON),
    )
    folder_rules = sa.table(
        "folder_access_rules",
        sa.column("id", sa.Integer),
        sa.column("folder_id", sa.String),
        sa.column("access_type", sa.String),
        sa.column("rule_data", sa.JSON),
    )

    for row in conn.execute(sa.select(document_rules)):
        _backfill_one_rule(
            conn,
            rules_table=rules_table,
            groups_table=groups_table,
            rights_table=rights_table,
            memberships_table=memberships_table,
            target_type="document",
            target_id=row.document_id,
            source_rule_id=row.id,
            access_type=row.access_type,
            rule_data=_parse_rule_data(row.rule_data),
        )

    for row in conn.execute(sa.select(folder_rules)):
        _backfill_one_rule(
            conn,
            rules_table=rules_table,
            groups_table=groups_table,
            rights_table=rights_table,
            memberships_table=memberships_table,
            target_type="directory",
            target_id=row.folder_id,
            source_rule_id=row.id,
            access_type=row.access_type,
            rule_data=_parse_rule_data(row.rule_data),
        )
