"""add generic system state storage

Revision ID: bb835a9f2cf4
Revises: 47c4c49d237b
Create Date: 2026-08-01 22:51:32.534415

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bb835a9f2cf4"
down_revision: str | Sequence[str] | None = "47c4c49d237b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_states",
        sa.Column("owner", sa.VARCHAR(length=255), nullable=False),
        sa.Column("state_key", sa.VARCHAR(length=128), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "revision > 0", name="ck_system_states_revision_positive"
        ),
        sa.CheckConstraint(
            "schema_version > 0",
            name="ck_system_states_schema_version_positive",
        ),
        sa.PrimaryKeyConstraint("owner", "state_key", name=op.f("pk_system_states")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_states")
    # ### end Alembic commands ###
