"""add document download risk control

Revision ID: c93cef4aa664
Revises: af95e9bae5fc
Create Date: 2026-07-28 19:46:47.973013

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c93cef4aa664"
down_revision: str | Sequence[str] | None = "af95e9bae5fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PERMISSION = "bypass_document_download_rate_limit"


def _permission_tables():
    return (
        sa.table("user_groups", sa.column("group_name", sa.String())),
        sa.table(
            "group_permissions",
            sa.column("group_name", sa.String()),
            sa.column("permission", sa.String()),
            sa.column("granted", sa.Boolean()),
            sa.column("start_time", sa.Double()),
            sa.column("end_time", sa.Double()),
        ),
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file_tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("issued_by_username", sa.VARCHAR(length=256), nullable=True)
        )
        batch_op.create_index(
            "ix_file_tasks_mode_status_end_time",
            ["mode", "status", "end_time"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_file_tasks_issued_by_username_users"),
            "users",
            ["issued_by_username"],
            ["username"],
            ondelete="SET NULL",
        )

    connection = op.get_bind()
    user_groups, group_permissions = _permission_tables()
    sysop_exists = connection.execute(
        sa.select(user_groups.c.group_name).where(
            user_groups.c.group_name == "sysop"
        )
    ).first()
    grant_exists = connection.execute(
        sa.select(group_permissions.c.permission).where(
            group_permissions.c.group_name == "sysop",
            group_permissions.c.permission == _PERMISSION,
            group_permissions.c.granted == sa.true(),
        )
    ).first()
    if sysop_exists and not grant_exists:
        connection.execute(
            group_permissions.insert().values(
                group_name="sysop",
                permission=_PERMISSION,
                granted=True,
                start_time=0.0,
                end_time=None,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _user_groups, group_permissions = _permission_tables()
    op.get_bind().execute(
        group_permissions.delete().where(
            group_permissions.c.group_name == "sysop",
            group_permissions.c.permission == _PERMISSION,
            group_permissions.c.granted == sa.true(),
        )
    )

    with op.batch_alter_table("file_tasks", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_file_tasks_issued_by_username_users"),
            type_="foreignkey",
        )
        batch_op.drop_index("ix_file_tasks_mode_status_end_time")
        batch_op.drop_column("issued_by_username")

    # ### end Alembic commands ###
