"""string revision ids

Revision ID: cb1df1f5c488
Revises: ddacf7741794
Create Date: 2026-05-26 12:38:40.654579

"""
import secrets
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1df1f5c488'
down_revision: Union[str, Sequence[str], None] = 'ddacf7741794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # 1. Fetch current mappings before schema changes
    revs = bind.execute(sa.text("SELECT id, parent_revision_id FROM document_revisions")).fetchall()
    docs = bind.execute(sa.text("SELECT id, current_revision_id FROM documents")).fetchall()

    id_map = {}
    rev_parents = {}
    for r_id, p_id in revs:
        old_str = str(r_id)
        id_map[old_str] = secrets.token_hex(32)
        rev_parents[old_str] = str(p_id) if p_id is not None else None

    doc_currents = {}
    for d_id, c_id in docs:
        doc_currents[str(d_id)] = str(c_id) if c_id is not None else None

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_revisions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('parent_revision_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('current_revision_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###

    # 2. Update data to new string IDs
    
    # Wipe FK references temporarily to avoid constraint errors
    bind.execute(sa.text("UPDATE documents SET current_revision_id = NULL"))
    bind.execute(sa.text("UPDATE document_revisions SET parent_revision_id = NULL"))

    # Update ID column
    for old_id, new_id in id_map.items():
        bind.execute(
            sa.text("UPDATE document_revisions SET id = :new_id WHERE id = :old_id"),
            {"new_id": new_id, "old_id": old_id}
        )

    # Restore parent_revision_id
    for old_id, old_parent_id in rev_parents.items():
        if old_parent_id is not None and old_parent_id in id_map:
            bind.execute(
                sa.text("UPDATE document_revisions SET parent_revision_id = :new_parent WHERE id = :new_id"),
                {"new_parent": id_map[old_parent_id], "new_id": id_map[old_id]}
            )

    # Restore documents.current_revision_id
    for doc_id, old_current_id in doc_currents.items():
        if old_current_id is not None and old_current_id in id_map:
            bind.execute(
                sa.text("UPDATE documents SET current_revision_id = :new_current WHERE id = :doc_id"),
                {"new_current": id_map[old_current_id], "doc_id": doc_id}
            )


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()

    # 1. Fetch current mappings before schema changes
    revs = bind.execute(sa.text("SELECT id, parent_revision_id FROM document_revisions")).fetchall()
    docs = bind.execute(sa.text("SELECT id, current_revision_id FROM documents")).fetchall()

    id_map = {}
    rev_parents = {}
    counter = 1
    
    for r_id, p_id in revs:
        old_str = str(r_id)
        id_map[old_str] = counter
        counter += 1
        rev_parents[old_str] = str(p_id) if p_id is not None else None

    doc_currents = {}
    for d_id, c_id in docs:
        doc_currents[str(d_id)] = str(c_id) if c_id is not None else None

    # Wipe FK references temporarily to avoid constraint errors
    bind.execute(sa.text("UPDATE documents SET current_revision_id = NULL"))
    bind.execute(sa.text("UPDATE document_revisions SET parent_revision_id = NULL"))

    # Update ID column
    for old_id, new_id in id_map.items():
        bind.execute(
            sa.text("UPDATE document_revisions SET id = :new_id WHERE id = :old_id"),
            {"new_id": new_id, "old_id": old_id}
        )

    # Restore parent_revision_id
    for old_id, old_parent_id in rev_parents.items():
        if old_parent_id is not None and old_parent_id in id_map:
            bind.execute(
                sa.text("UPDATE document_revisions SET parent_revision_id = :new_parent WHERE id = :new_id"),
                {"new_parent": id_map[old_parent_id], "new_id": id_map[old_id]}
            )

    # Restore documents.current_revision_id
    for doc_id, old_current_id in doc_currents.items():
        if old_current_id is not None and old_current_id in id_map:
            bind.execute(
                sa.text("UPDATE documents SET current_revision_id = :new_current WHERE id = :doc_id"),
                {"new_current": id_map[old_current_id], "doc_id": doc_id}
            )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('current_revision_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('document_revisions', schema=None) as batch_op:
        batch_op.alter_column('parent_revision_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
