"""modify userblock_entries id type

Revision ID: ccd985e08120
Revises: 148e5acbbe5c
Create Date: 2026-02-22 22:30:26.345687

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd985e08120'
down_revision: str | Sequence[str] | None = '148e5acbbe5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userblock_entries', schema=None) as batch_op:
        batch_op.alter_column('block_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('userblock_sub_entries', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userblock_sub_entries', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('userblock_entries', schema=None) as batch_op:
        batch_op.alter_column('block_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
