"""support download resume

Revision ID: ddacf7741794
Revises: 5b4437a79292
Create Date: 2026-05-12 18:38:04.736202

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddacf7741794'
down_revision: str | Sequence[str] | None = '5b4437a79292'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_key', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_tasks', schema=None) as batch_op:
        batch_op.drop_column('encryption_key')

    # ### end Alembic commands ###
