"""fix delimiter injection

Revision ID: e09c3ecf8f0a
Revises: 50df72915860
Create Date: 2026-04-06 01:46:11.263975

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09c3ecf8f0a'
down_revision: str | Sequence[str] | None = '50df72915860'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_login_security',
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip_address', name=op.f('pk_ip_login_security'))
    )
    op.execute("DELETE FROM login_security")
    with op.batch_alter_table('login_security', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=False))
        batch_op.create_index(batch_op.f('ix_login_security_ip_address'), ['ip_address'], unique=False)
        batch_op.drop_column('identifier')
        batch_op.create_primary_key('pk_login_security', ['username', 'ip_address'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM login_security")
    # Restore the original single-column primary key on `identifier`.
    # Since the upgrade created a composite PK on (username, ip_address),
    # we drop that PK and recreate the `identifier` primary key.
    with op.batch_alter_table('login_security', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.VARCHAR(length=128), nullable=False))
        # Attempt to drop any existing primary key constraint created by the upgrade.
        try:
            batch_op.drop_constraint(batch_op.f('pk_login_security'), type_='primary')
        except Exception:
            # Some backends may use different PK names; ignore and proceed to create the PK.
            pass
        # Create primary key on identifier to match pre-migration schema
        try:
            batch_op.create_primary_key(batch_op.f('pk_login_security'), ['identifier'])
        except Exception:
            # If creation via batch_op fails for a backend, fall back to raw SQL.
            op.execute("ALTER TABLE login_security ADD PRIMARY KEY (identifier)")

        # drop index on ip_address (if present) and remove new columns
        try:
            batch_op.drop_index(batch_op.f('ix_login_security_ip_address'))
        except Exception:
            pass
        # Now safe to drop the composite columns
        try:
            batch_op.drop_column('ip_address')
        except Exception:
            pass
        try:
            batch_op.drop_column('username')
        except Exception:
            pass

    op.drop_table('ip_login_security')
    # ### end Alembic commands ###
